CREATE TABLE products (
product_id INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
DESCRIPTION TEXT,
price DECIMAL(10,2) NOT NULL,
quantity INT NOT NULL DEFAULT 0,
image_url VARCHAR (50),
category_id INT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (category_id) REFERENCES categories(category_id)
);